### ISSUE TITLE
Playwright tests are failing

### ISSUE THREAD

**Issue by bleggett** [opentdf/frontend#53] opened 2022-04-26 19:35 UTC
At least they're failing locally for me.

When I try to load up `localhost:65432/` manually, page flickers and then finally gives me this:
![Screen Shot 2022-04-26 at 3 34 20 PM](https://user-images.githubusercontent.com/854255/165378379-cbdbd8b5-dc07-4456-b85e-f8e3e6a3b07a.png)

which is probably why they're failing.

**Comment by ysizarie-virtru** [comment] 2022-05-04 09:15
This should be fixed already

**Comment by sievdokymov-virtru** [comment] 2022-07-27 09:13
Yes, the issue is already fixed in scope of PLAT-1726 - https://github.com/opentdf/backend/pull/129

**Closed by sievdokymov-virtru** 2022-07-27 09:13 UTC
